I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 326, in script
    none ""
  File "game/screens.rpy", line 1601, in execute
    screen monologue(dialogue):
  File "game/screens.rpy", line 1601, in execute
    screen monologue(dialogue):
  File "game/screens.rpy", line 1603, in execute
    $ current_dialogue = monologue_list[0]
  File "game/screens.rpy", line 1603, in <module>
    $ current_dialogue = monologue_list[0]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 326, in script
    none ""
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\character.py", line 1455, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\character.py", line 1106, in do_display
    display_say(who,
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\character.py", line 803, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 1601, in execute
    screen monologue(dialogue):
  File "game/screens.rpy", line 1601, in execute
    screen monologue(dialogue):
  File "game/screens.rpy", line 1603, in execute
    $ current_dialogue = monologue_list[0]
  File "game/screens.rpy", line 1603, in <module>
    $ current_dialogue = monologue_list[0]
  File "C:\Users\jkk12\renpy-8.3.3-sdk\renpy\revertable.py", line 214, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24111502
great mediocrity 1.0
Tue Jan 21 13:42:33 2025
